spring:
  redis:
    password:
    cluster:
      nodes: 47.96.154.52:6381,47.96.154.52:6382,47.96.154.52:6383
      max-redirects: 3
#    lettuce:
#      pool:
#        max-idle: 16
#        max-active: 32
#        min-idle: 8